apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-container-platform
    role: klovercloud
  name: app-container-platform
  namespace: klovercloud
spec:
  ports:
    - name: http-rest
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: app-container-platform
    role: klovercloud
  type: ClusterIP
